# Generated by Django 4.2.7 on 2023-11-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sub_category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
